# Build Stage
FROM node:latest AS build-stage
WORKDIR /app

# Copy only package.json and package-lock.json for dependency installation
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY ./ ./
EXPOSE 8080
RUN npm run build

# Production Stage
FROM nginx AS production-stage
WORKDIR /app

# Copy the built files from the build stage
COPY --from=build-stage /app/dist /app

# Copy the custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf